name: "Install Casper node CI environment"
description: "Installs the common CI environment for the Casper blockchain node"
runs:
  using: composite
  steps:
    - name: Get nightly toolchain from smart_contracts dir
      id: nightly-toolchain
      run: echo "::set-output name=version::$(cat smart_contracts/rust-toolchain)"
      shell: bash

    - name: Get stable from rust-toolchain.toml
      id: stable-toolchain
      run: echo "::set-output name=version::$(sed -nr 's/channel\s+=\s+\"(.*)\"/\1/p' rust-toolchain.toml)"
      shell: bash

    - name: Install Toolchain - Stable
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #tag v1.0.7
      with:
        profile: minimal
        toolchain: ${{ steps.stable-toolchain.outputs.version }}
        components: rustfmt, clippy
        target: wasm32-unknown-unknown

    - name: Install Toolchain - Nightly
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #tag v1.0.7
      with:
        profile: minimal
        toolchain: ${{ steps.nightly-toolchain.outputs.version }}
        components: rustfmt, clippy
        target: wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v1

    - name: Provide dummy `cachepot`
      run: |
        mkdir -p /tmp/overlay
        ln -s $(which true) /tmp/overlay/cachepot
        echo "/tmp/overlay" >> ${GITHUB_PATH}
      shell: bash

    - run: sudo apt-get update -y
      shell: bash
    - run: sudo apt-get install -y python3-pip supervisor socat
      shell: bash
    - run: sudo pip install tomlkit toml
      shell: bash
